### ISSUE TITLE
application hang on macOS

### ISSUE THREAD

**Issue by boxy-boy** [chrislo27/PolyrhythmMania#14]
attempting to run the .jar on mac os throws these two errors nonstop and hangs. i gave the jar full privileges, and used the same command to start the .jar used in both launch scripts for windows and linux
![Screen Shot 2021-08-29 at 12 24 13 AM](https://user-images.githubusercontent.com/69577030/131242393-21bac35b-f61f-46f1-a8eb-8e968df7e794.png)

**Comment by chrislo27** [comment]
[macOS is not an officially supported platform,](https://github.com/chrislo27/PolyrhythmMania#installation-instructions) so I cannot offer much.

However, you can try passing in the VM argument `-XstartOnFirstThread`. Edit the shell script so that the parameter is something like as follows:
```
java -jar -XstartOnFirstThread bin/PolyrhythmMania.jar
```
