### ISSUE TITLE
Add a bash script for launching the game on Mac

### ISSUE THREAD

**Issue by CelestialAmber** [chrislo27/PolyrhythmMania#29]
I noticed there wasn't a bash script for launching the game on Mac, so I tried to just run the Linux sh file and got an error. I was able to fix the error with a simple modification to the java command in the script, so all that would have to be done to allow the game to work on Mac is just adding this bash script to the build folder, and modifying the portable script like I did with the regular one for that to also work (the script is attached below).
[play_mac.sh.zip](https://github.com/chrislo27/PolyrhythmMania/files/7165521/play_mac.sh.zip)

**Comment by chrislo27** [comment]
Per the [front page README](https://github.com/chrislo27/PolyrhythmMania#installation-instructions), macOS is **not** a supported operating system. This means that I can't offer bug support or the guarantee that the game will even run on macOS, so I don't want to offer a launch script directly. Other Mac users are free to use this launch script if it works for them though.

For documentation purposes: the added VM argument is `-XstartOnFirstThread` per GLFW requirements.

**Comment by CelestialAmber** [comment]
I understand. Thanks for replying anyways.
