### ISSUE TITLE
[Bug]: Endless mode randomly goes back to the endless screen

### ISSUE THREAD

**Issue by notpolyrhythmic** [chrislo27/PolyrhythmMania#30]
### Version

v1.0.2

### Operating System

Windows 10

### Problem Description

I got up to around 76 on endless mode and then the game went back to the endless seed select screen

### Steps to Reproduce Problem

Not quite sure how to reproduce it, it might be seed specific if that's a thing since I've played up to 60 ish before on other levels and got the same issue but I can't get the seed I was just on back

**Comment by chrislo27** [comment]
Unfortunately, without a consistent way to reproduce the problem, I can't verify that the problem exists nor start fixing it if it does exist.

At the very least, more info about the endless mode settings you were using would be helpful. What about your life count? Were you at 1/close to 1 at the time? Did you previously get a game over and then select Start Over from the pause menu while it was showing your score? These details are very helpful to me.

**Comment by chrislo27** [comment]
I think I may have found steps to reproduce the issue but **you should verify** that this is the same behaviour you're describing.

1. Start Endless Mode
2. Don't do anything. Exhaust all your lives
3. While it shows the Game Over screen, pause and Start Over.
4.. Play normally, don't lose any lives
5. The game will close out to the main menu shortly after the point where you had the original Game Over

**Comment by notpolyrhythmic** [comment]
Yep thats it,

**Comment by chrislo27** [comment]
Thanks. This issue will be fixed for the next release. I will close this issue myself when that release is out.
