### ISSUE TITLE
Option to force GBA or HD textures

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/PolyrhythmMania#33]
### Discussed in https://github.com/chrislo27/PolyrhythmMania/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **goldenyoshi22** September 23, 2021</sup>
An option (maybe in "VIDEO" tab) to either force the GBA or HD texture, or don't force a texture. (Don't force by default)

## Justification
The reason for this is because there are many slow computers like mine, and it lags with the HD texture.

## Potential Issues
If there are maps that use custom textures, it may look weird. You could maybe have an option to let custom textures override or not.

# 

I am typing this on mobile, so I can't make an image mockup. If I could, I would make a checkmark with the text "Force texture". When it's on, an arrow switch appears with the options, "GBA" and "HD".</div>

The option will be added to a new Graphics settings menu with a dropdown to either not force any texture, to force GBA textures, or to force HD textures. There will also be a checkbox to enable/disable custom textures.

**Comment by TheEggo55** [comment]
Can I also suggest the ability to choose specific modes to have a certain texture pack (ie. Tutorials, Endless Mode, Daily Challenge) that does not affect the rest of the game?

**Comment by chrislo27** [comment]
I think the concern is that the built-in modes don't let you change the pack at all, whereas with a custom level you can edit it. I can look into adding the option though to affect/not affect built-in modes.

**Comment by chrislo27** [comment]
The setting has been implemented for the v1.1 feature update release, along with a similar option for forcing use of the default tileset palette. Setting either Use GBA only or Use HD only will also disable custom textures.
![image](https://user-images.githubusercontent.com/6299069/134781089-e2012d26-20dc-4e33-b4fa-2209f86592cd.png)
