### ISSUE TITLE
Make Tempo Change tool support arrow keys and WASD

### ISSUE THREAD

**Issue by TerrariaTree** [chrislo27/PolyrhythmMania#35]
I have to use scrolling, the problem is, I use a laptop with a touchpad, making it extremely hard to get the tempo just right.
RHRE3 supports this, but apparently, this doesnt work here
If you could add this, it would mean a lot to me! Thanks for reading
-Terraria Tree

**Comment by chrislo27** [comment]
This is already implemented in the Editor Settings. 
![image](https://user-images.githubusercontent.com/6299069/136246155-8832fd2f-0b4c-4927-9004-2b63228afbe9.png)
