### ISSUE TITLE
[Bug]: Error while trying to load a level in the editor or when I try to play it. 

### ISSUE THREAD

**Issue by Unnamedspaceuser** [chrislo27/PolyrhythmMania#36]
### Version

v1.0.2

### Operating System

Windows 10

### Problem Description

Hello, I'd like to report a bug that happened to me. I was editing a level in my laptop and then put it in sleep mode with the editor still open, and when I opened back my laptop after a while I noticed that the level stopped autosaving like it normally does. At first, I did not pay to much attention to it since I thought I could just save manually, which I did, and the editor even told me that the saves were succesful. But, when I finished the level and seved once more and tried to play it through the main menu but an error message appeared saying the the level could not be loaded, and the same message poped up when I tried to load the level in the editor, which you can see the following screenshots I took. I don't know exactly what caused this, but I think it's related to the fact that I put my laptop in sleep mode with the editor open. So I was hoping that there was a way to make my level to load properly, that would be great, thanks. 
      
![edit error](https://user-images.githubusercontent.com/91995907/136298992-d3417a9c-af88-4d99-8e39-183c483523c7.PNG)
![load error](https://user-images.githubusercontent.com/91995907/136298995-12e16894-7c60-4049-85d2-40bc843fcaa1.PNG)
  

### Steps to Reproduce Problem

1. Create a new polyrhythm mania map.
2. Put some stuff in it .
3. Put your PC on sleep mode for like an hour.  
4. Open your PC and save the level.
5. Return to main menu and try to play it or open it again through the editor. 

*As I said, I don't what caused this exactly, so this is just an assumption.  

### (Optional) Other useful information

In any case, here's also the link to a google drive folder in which there's the level I can't get to load, it is called "WISH". 
Link: https://drive.google.com/drive/folders/1GN9E2UTAmP20fP-KWcVrOTRpy90DNH4w?usp=sharing

**Comment by chrislo27** [comment]
I've been doing some debugging with the limited information I have so far and it may be related to resource management while loading a level. I have patched it in commit 7f4a1702333ae24a402e6a96074ab1aad3f1dc6a but I still need your log files to verify.

As for your level, I've edited it to have its music removed, please check that it can be loaded now: [WISH - nomusic.zip](https://github.com/chrislo27/PolyrhythmMania/files/7298945/WISH.-.nomusic.zip) (You'll have to put the music back yourself.)

**Comment by Unnamedspaceuser** [comment]
It worked, it finally loads again! Thank you, thank you very much!! I will put the music back myself no problem. But thanks!

**Comment by chrislo27** [comment]
Thank you. I can confirm that one of the log files contains the same error I encountered with regards to resource management.

Please leave this issue open as I will close it when the next update is released.
