### ISSUE TITLE
Website for translation

### ISSUE THREAD

**Issue by Funmoring46** [chrislo27/PolyrhythmMania#56]
I would like to help translating. that's it lol

**Comment by chrislo27** [comment]
Can you please provide more details? Such as, what language you would like to translate to, your previous experience with localization, etc.

**Comment by Funmoring46** [comment]
I'm actually asking if there is a website to do it, and I said the wrong thing I don't really want to translate but I just saw that English was the only language available.

**Comment by chrislo27** [comment]
There is no website hub for translating, sorry. The project isn't big enough (or active enough) where I could use something like Crowdin, for example.
