### ISSUE TITLE
Ability to turn off the spotlights, especially in Story Mode

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/PolyrhythmMania#58]
### Discussed in https://github.com/chrislo27/PolyrhythmMania/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **Weyverling** August 14, 2023</sup>
[version 2.0.2-20230512a_win64]

Request: Some way to turn spotlights off as an additional Graphics & Accessibility option

Justification (/ bug report):
When the spotlights turn on in the "phase change" for the boss my computer lags out and none of my inputs can come out correctly and I die near-instantly. I think this is just a problem with my setup and probably can't be fixed, but I'd like to have some way of circumventing this lag spike to have a better chance of completing Story Mode. I'm not sure if it comes under Reduce In-game Motion normally but I have that checked too, and Robot Mode still uses the spotlights.

Attached is me trying to show this lag spike. I don't know if it just comes off as a skill issue but every single time the spotlights hit my run has died, this is just the first time I got it on tape. I was doing better before but I cropped the video for size.
![image](https://github.com/chrislo27/PolyrhythmMania/assets/83324457/1009aff5-cabf-4881-98d7-d5dfe642ebea)
Also for some reason this game loves to use 100% of my GPU. The only things I have open right now are Firefox to write this and Polyrhythm Mania. I've made the resolution as low as I can and capped the frame rate at 30 to try and counteract the spikes but I don't think that's helped either.
https://github.com/chrislo27/PolyrhythmMania/assets/83324457/5e4ade34-922e-441c-badd-fb21104c1983

</div>

**Comment by SalTeyJek004** [comment]
oh yeah im having issues with the spotlights as well

**Comment by chrislo27** [comment]
This feature has been implemented for the next feature update, v2.1.0. You will be able to find it in the Graphics & Accessibility menu.

![image](https://github.com/chrislo27/PolyrhythmMania/assets/6299069/d50bce61-0636-4511-b100-5461bbf85522)

I have marked this issue as Fixed and will close it when the update is released.

**Comment by chrislo27** [comment]
[This feature has been released as of version 2.1.0.](https://github.com/chrislo27/PolyrhythmMania/releases/tag/v2.1.0)
