### ISSUE TITLE
[Bug]: custom files wont show up

### ISSUE THREAD

**Issue by PLGGitHub1** [chrislo27/PolyrhythmMania#61]
### Version

v2.1.1-20231114a

### Operating System

Windows 11

### Problem Description

on explorer:
![Screenshot 2024-06-13 100952](https://github.com/chrislo27/PolyrhythmMania/assets/167148240/afbc61f3-9dba-4691-9991-a5514648b7f2)
on polyrhythm mania:
![Screenshot 2024-06-13 100300](https://github.com/chrislo27/PolyrhythmMania/assets/167148240/ee9932c5-d129-43fd-a00f-f40a7ae46934)

### Steps to Reproduce Problem

1. open 2. edit 3. export

### Relevant log output

```shell
cant put logs😭😭😭😭
```

**Comment by chrislo27** [comment]
You are looking for your files in a different folder than the popup. You need to change what folder you're looking at when you're loading a level -- for example if you're saving your levels in the Downloads folder, look at the Downloads folder when loading a level.
